# --- General options --- #

# Name of website
title: Dr. Yanxia Zhang

# Short description of your site
description: Researcher in Computer Vision, Machine Learning and HCI

email_contact: yzhang [at] fxpal [dot] com

# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: ""

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-40281333-1"

# Google Tag Manager ID
#gtm: ""

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
